In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
dataset=pd.read_csv(r'C:\Users\KAVITHA\Desktop\firstone.csv')
dataset

created_at  fuel  speed  gps_fixed  ignition_status        lat  \
0     19-04-2019 00:00   144   21.6          1                1  23.362417   
1     19-04-2019 00:00   144   20.9          1                1  23.362517   
2     19-04-2019 00:00   142   19.9          1                1  23.362641   
3     19-04-2019 00:00   142   19.4          1                1  23.362737   
4     19-04-2019 00:00   144   19.2          1                1  23.362831   
5     19-04-2019 00:00   144   18.1          1                1  23.362918   
6     19-04-2019 00:00   144   17.3          1                1  23.362994   
7     19-04-2019 00:00   142   17.9          1                1  23.363069   
8     19-04-2019 00:00   142   19.0          1                1  23.363151   
9     19-04-2019 00:00   142   19.8          1                1  23.363238   
10    19-04-2019 00:00   142   20.2          1                1  23.363331   
11    19-04-2019 00:00   144   20.4          1                1  23.363421   
12    19-04-2019 00:00   144   21.1          1                1  23.363516   
13    19-04-2019 00:00   146   20.6          1                1  23.363608   
14    19-04-2019 00:00   144   20.7          1                1  23.363705   
15    19-04-2019 00:00   144   18.7          1                1  23.363842   
16    19-04-2019 00:00   142   16.6          1                1  23.363936   
17    19-04-2019 00:00   142   15.1          1                1  23.364014   
18    19-04-2019 00:00   142   14.5          1                1  23.364050   
19    19-04-2019 00:00   142   15.0          1                1  23.364087   
20    19-04-2019 00:01   138   16.8          1                1  23.364164   
21    19-04-2019 00:01   140   17.6          1                1  23.364266   
22    19-04-2019 00:01   140   19.7          1                1  23.364379   
23    19-04-2019 00:01   140   20.5          1                1  23.364509   
24    19-04-2019 00:01   140   21.2          1                1  23.364648   
25    19-04-2019 00:01   142   21.7          1                1  23.364778   
26    19-04-2019 00:01   142   21.0          1                1  23.364883   
27    19-04-2019 00:01   142   18.4          1                1  23.364967   
28    19-04-2019 00:01   132   18.8          1                1  23.365085   
29    19-04-2019 00:01   132   19.6          1                1  23.365143   
...                ...   ...    ...        ...              ...        ...   
3146  19-04-2019 02:58   122    0.3          1                0  23.339280   
3147  19-04-2019 02:58   122    0.8          1                0  23.339280   
3148  19-04-2019 02:58   122    2.0          1                0  23.339273   
3149  19-04-2019 02:58   122    1.6          1                0  23.339260   
3150  19-04-2019 02:58   122    1.2          1                0  23.339263   
3151  19-04-2019 02:58   122    1.1          1                0  23.339263   
3152  19-04-2019 02:58   122    0.4          1                0  23.339263   
3153  19-04-2019 02:58   122    0.2          1                0  23.339263   
3154  19-04-2019 02:58   122    0.4          1                0  23.339263   
3155  19-04-2019 02:58   122    0.5          1                0  23.339263   
3156  19-04-2019 02:58   122    1.1          1                0  23.339263   
3157  19-04-2019 02:59   122    1.6          1                0  23.339265   
3158  19-04-2019 02:59   122    0.3          1                0  23.339268   
3159  19-04-2019 02:59   122    0.3          1                0  23.339268   
3160  19-04-2019 02:59   122    0.2          1                0  23.339268   
3161  19-04-2019 02:59   122    0.0          1                0  23.339268   
3162  19-04-2019 02:59   122    0.5          1                0  23.339268   
3163  19-04-2019 02:59   122    0.7          1                0  23.339268   
3164  19-04-2019 02:59   122    0.4          1                0  23.339268   
3165  19-04-2019 02:59   122    0.

In [3]:
x=dataset.iloc[:, 1:7].values
y=dataset.iloc[:,7].values

In [4]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
x[:,0]=labelencoder.fit_transform(x[:,0])
x[:,0]

array([13., 13., 12., ...,  3.,  3.,  3.])

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
x[:,0]=labelencoder.fit_transform(x[:,0])
onehotencoder=OneHotEncoder(categorical_features=[0])
x=onehotencoder.fit_transform(x).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [7]:
x_train

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
        23.373797  , 85.268445  ],
       [ 0.        ,  0.        ,  0.        , ...,  1.        ,
        23.34135417, 85.20164383],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        23.3393485 , 85.20062117],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  1.        ,
        23.37029333, 85.258764  ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        23.3393065 , 85.20069417],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        23.33908983, 85.2007125 ]])

In [8]:
y_train

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [11]:
y_pred=classifier.predict(x_test)

In [12]:
y_pred

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)


0.9905660377358491